# Create render.yaml
cat > render.yaml << EOL
services:
  - type: web
    name: my-dashboards
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
EOL